Repository mapcrafter/mapcrafter, pull requests merged in 2020-06, with the labels that each got.

#301 Blockcrafter step-by-step page
  MCVERSION
  VERSION
  docs/blockcrafter.rst
  docs/configuration.rst
  docs/img/map_render_view_isometric.png
  docs/img/map_render_view_side.png
  docs/img/map_render_view_topdown.png
  docs/index.rst
Labels: Ready for review

#320 Add note about using <br> in markers
  docs/configuration.rst
Labels: Low priority

#367 Minor updates towards 1.13+
  .editorconfig
  CHANGELOG.md
  MCVERSION
  README.md
  VERSION
  docs/img/map_render_view_isometric.png
  docs/img/map_render_view_side.png
  docs/img/map_render_view_topdown.png
  src/mapcraftercore/version.sh
Labels: Documentation, Minecraft 1.13, Ready for review, Technical debt
